//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileWithEncryption.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileWithoutEncript
    {
        public long fileid { get; set; }
        public byte[] FileContent { get; set; }
    }
}
